### ISSUE TITLE
Remove patch version from go directive in go.mod

### ISSUE THREAD

**Issue by joshkaplinsky** [MicahParks/keyfunc#105]
Is it possible to remove the patch version from the go directive in the go.mod file (e.g., `1.21.5` -> `1.21`)? This requires users of this package to specify a Go version greater than or equal to the required version. In our workflow, we do not always have the latest patch version immediately available to build against.

**Comment by MicahParks** [comment]
Yeah, I can remove that later today (eastern USA). I don't think it would be considered a breaking change.

**Comment by joshkaplinsky** [comment]
Thanks, much appreciated! I agree, it shouldn't be a breaking change. Any patch version would be compatible with the same minor version.

**Comment by MicahParks** [comment]
This change was made in this PR:
https://github.com/MicahParks/keyfunc/pull/106

Please see the newest tag `v3.2.4`

**Comment by joshkaplinsky** [comment]
Thank you for the fast response!
