### ISSUE TITLE
Provider name and make an action

### ISSUE THREAD

**Issue by rytsh** [MicahParks/keyfunc#111]
If we add the provider name when creating the multi jwks, we can also add some actions before or after if kid found for that provider name and we can run some functions for that.

For example I have x and y cert providers but I want to make different actions when token from x or y.

This is some a feature request and just an idea.

**Comment by MicahParks** [comment]
I believe this feature request is a for adding optional callbacks. Please correct me if I've read that incorrectly.

At the moment, I think this is out of scope for this package, but I'll leave this issue open for a while to see if there is interest from others.

**Comment by MicahParks** [comment]
I'm going to close this issue for now. If others want to express interest for an optional callback system, please do comment on this issue :+1:
