### ISSUE TITLE
keyfunc.JWKs: Keys field undefined in v0.8.0

### ISSUE THREAD

**Issue by tillkuhn** [MicahParks/keyfunc#16]
After upgrading from v0.7.0 to v0.8.0 I get the following compile time error:

```
jwks.Keys undefined (type *keyfunc.JWKs has no field or method Keys)
```
It seems the previous JWKs struct exported a field `Keys` of type ` map[string]*JSONKey`, which is now gone. What is the alternative to access the keys for a Set?

Thanks,
Till

**Comment by tillkuhn** [comment]
Thanks for the thorough explanation. You're right, at some point the above code fails with a `fatal error: concurrent map read and map write`. I had to dig a bit to find out how the Keys were actually used in the application. We recently activated Renovate with automerge for minor and patch versions, and that's where I noticed the sudden compile error with v0.8.0!

It turns out the `Keys` was only used to validate that the JWKs contains at least one key, and check on the algorithm. So it's read-only, and also not super important for the use case, since `Keyfunc` does the actual work under the hood. I keep the issue open if you still want to perform some actions, but feel free to close it. Maybe in future you can add a comment on the Tag, or add a `CHANGELOG.md` (or prominent README section) for breaking changes with new versions. This could avoid issues and, give some background on the motivation for the change. Also noticed KeyFunc was renamed to Keyfunc. But hey, it's open source and I'm happy you share your work. Have a nice weekend // Till

**Comment by MicahParks** [comment]
As a suggestion, I'd turn off "Renovate with automerge" for packages in pre-release, like this one. Breaking changes can occur at any version bump until there is a full release. Here's a reference for Go packages in the first-unstable release like this one: https://golang.org/doc/modules/release-workflow#first-unstable

It's certainly useful to check that keys exist in the `JWKs`. I'll add that read-only method called `KIDs` that returns a slice of the `kid`s found in the JWKs. Let me know if that does not cover your use case. After that, I'll close this issue. Should be done after work today.

As a note, I'm currently in the process of drafting a PR for the upstream `github.com/golang-jwt/jwt/v4`: https://github.com/golang-jwt/jwt/pull/105. It's my goal to do a `v1.0.0` release for this package if that PR is merged, then not introduce any more breaking changes. If this upstream PR goes through and you're using `github.com/golang-jwt/jwt/v4`, I'd recommend removing `github.com/MicahParks/keyfunc` as a dependency and using the `github.com/golang-jwt/jwt/v4/keyfunc` package. The `github.com/MicahParks/keyfunc` will still be maintained and kept up to date with upstream, for compatibility purposes.

**Comment by tillkuhn** [comment]
Sounds great! We don't use automerge for mission critical apps, and it's linked with the CI/CD Pipelines. So if build or tests fail, nothing gets merged or even deployed to staging, and the developer gets notified. That's a good compromise for most  of my standard use cases. And yes, I'm using `golang-jwt/jwt/v4` and would appreciate if your utils become part of it. As for my use case, a KIDs slice would be sufficient, thanks you very much. If you want me to test an unreleased version, just let me know!

**Comment by MicahParks** [comment]
@tillkuhn Please see the recent addition in `v0.8.2`

**Comment by tillkuhn** [comment]
It works, thanks for the quick fix!
