### ISSUE TITLE
panic: runtime error: slice bounds out of range [1:0]

### ISSUE THREAD

**Issue by conor-nsurely** [MicahParks/keyfunc#27]
I originally opened this issue on "github.com/golang-jwt/jwt" , they thought it was more likely to be an issue with this library instead.

I am trying to parse a JWT generated by Keycloak using a public key(keyfunc.JWKS) from the appropriate Keycloak realm.

The JWT is valid according to jwt.io. jwt.ParseUnverified() works fine too, so the problem doesn't seem to be the token.

It throws this error upon parsing with jwt.Parse() :
`panic: runtime error: slice bounds out of range [1:0]`

I am creating the jwks using this library, like so:
```            
                url := "http://keycloak:8080/auth/realms/{realm_id}/protocol/openid-connect/certs"
		refreshInterval := time.Hour
		options := keyfunc.Options{
			RefreshInterval: refreshInterval,
			RefreshErrorHandler: func(err error) {
				logging.Log.Printf("There was an error with the jwt.KeyFunc\nError: %s", err.Error())
			},
		}
		jwks, err := keyfunc.Get(url, options)
```
This creates without error. 

The error is thrown by `jwt.Parse()` in the code below.
```

	verified_token, err := jwt.Parse(token, jwks.Keyfunc)
	if err != nil {
		logging.Log.Fatalf("Failed to parse the JWT.\nError: %s", err.Error())
	}

	if !verified_token.Valid {
		logging.Log.Fatalf("The token is not valid.")
	}
```

JWKS is using the structs from the examples.

```
	type ErrorHandler func(err error)
	type GivenKey struct {
		inter interface{}
	}
	type JWKS struct {
		cancel              context.CancelFunc
		client              *http.Client
		ctx                 context.Context
		raw                 []byte
		givenKeys           map[string]GivenKey
		givenKIDOverride    bool
		jwksURL             string
		keys                map[string]interface{}
		mux                 sync.RWMutex
		refreshErrorHandler ErrorHandler
		refreshInterval     time.Duration
		refreshRateLimit    time.Duration
		refreshRequests     chan context.CancelFunc
		refreshTimeout      time.Duration
		refreshUnknownKID   bool
	}
```

Any idea what's going on here?

**Comment by MicahParks** [comment]
Here is the link to the previous issue: https://github.com/golang-jwt/jwt/issues/167

I don't know what's going on quite yet, I'd need more information to be helpful to you.

Could you provide the following:
___
## An example JWT

I'd probably need this to reproduce the bug.
___
## The panic call stack

You likely know what this is, but just to be clear, it looks like this:
```
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
main.myFunc(...)
	/home/micah/main.go:8
main.main()
	/home/micah/main.go:4 +0x29
```
This will help me track down any bugs by enumerating the lines that lead to a panic.
___
## A snippet of your code

If you could upload the function/lines surrounding the panic it'd help give context. If it's an open source project, a link would be best.

**Comment by conor-nsurely** [comment]
Hey Micah

## Example JWT

`eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJvTjNUVllqQVNreVozekFhblFVLW0tU1RpZ2ZjM09aRnRqSVF3YUJ4MjhvIn0.eyJleHAiOjE2NDUwNzQwNjYsImlhdCI6MTY0NTA3Mzc2NiwianRpIjoiZDAxOWQ5YTctYmIyOS00ZjFlLThlZmItYTU1MzQ2MGRmOTgzIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zLzkwZmNmZjNkOGUzZmJiOWRjM2VmZWNkYSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJkYTg4MmZjNy00N2RmLTRmZjQtYjMzMy01ZDRlYmFjMzM2ZjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJweXRob24ta2V5Y2xvYWsiLCJzZXNzaW9uX3N0YXRlIjoiYzBiNjJjZDktM2Q1Yy00YWVlLWI1NTItMGZmMDRlYmVkZjZkIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwiZGVmYXVsdC1yb2xlcy05MGZjZmYzZDhlM2ZiYjlkYzNlZmVjZGEiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJzaWQiOiJjMGI2MmNkOS0zZDVjLTRhZWUtYjU1Mi0wZmYwNGViZWRmNmQiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJ0aW0gd2Zhd2YiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ0ZXN0dDJzZXRAd2Z3Zi5jb20iLCJnaXZlbl9uYW1lIjoidGltIiwiZmFtaWx5X25hbWUiOiJ3ZmF3ZiIsImVtYWlsIjoidGVzdHQyc2V0QHdmd2YuY29tIn0.MAV77ttj4T-Ewfq3BjW_km9L9XTT7a4QvH9UDsJIGa2JUuPonksaAx6bf7af_I1n_INwjTkVVAIqxSmRKGsqyI0Vm1qlRKMU64OPcMTdvD-LZg5Br6a_uGWqKfQ59-1YV_lJqTiGN8hwbv1_zpAKaVxHTOimWFvyLyvvi9Bedz6mcDPZjBdCnDVfKd9aOomr03LAYUzACPF0XPOV6ydqlgtK_1JVlu4pEiLHSKZVTx8-_4IVm1gJItaBnUVfOyk8m8uFqzfbeH4bWgGSf6fALjvf6yS-aeuf35zuArn3qGZ5s_LL8C6zzTrIkMWCfXWepFt5hnHqBKY8cwML1L-cFw`


## The panic call stack
Logging library might be obfuscating things here possibly, brand new to Go.
```
trip-api-test  | panic: runtime error: slice bounds out of range [1:0]
trip-api-test  | 
trip-api-test  | goroutine 6 [running]:
trip-api-test  | github.com/coralogix/go-coralogix-sdk.(*LoggerManager).SendBulk(0xc0000eeb80, 0x52)
trip-api-test  |        /go/pkg/mod/github.com/coralogix/go-coralogix-sdk@v1.0.2/manager.go:136 +0x24a
trip-api-test  | github.com/coralogix/go-coralogix-sdk.(*LoggerManager).Run(0xc0000eeb80)
trip-api-test  |        /go/pkg/mod/github.com/coralogix/go-coralogix-sdk@v1.0.2/manager.go:153 +0xd2
trip-api-test  | created by github.com/coralogix/go-coralogix-sdk.NewCoralogixHook
trip-api-test  |        /go/pkg/mod/github.com/coralogix/go-coralogix-sdk@v1.0.2/hook.go:23 +0xcf
trip-api-test exited with code 2
```
## Code Snippet
Not open source unfortunately, but this snippet should have everything you need hopefully. Minimal( non) working example
You'll have to change the logging for this to run probably, but left in just in case it's relevant
```
import (
	"context"
	"fmt"
	"net/http"
	"strings"
	"sync"
	"time"
	"github.com/MicahParks/keyfunc"
	"github.com/golang-jwt/jwt/v4"
	"github.com/ROH/main/app/logging"
)

func verify_bearer(token string) bool {

	type ErrorHandler func(err error)
	type GivenKey struct {
		inter interface{}
	}
	type JWKS struct {
		cancel              context.CancelFunc
		client              *http.Client
		ctx                 context.Context
		raw                 []byte
		givenKeys           map[string]GivenKey
		givenKIDOverride    bool
		jwksURL             string
		keys                map[string]interface{}
		mux                 sync.RWMutex
		refreshErrorHandler ErrorHandler
		refreshInterval     time.Duration
		refreshRateLimit    time.Duration
		refreshRequests     chan context.CancelFunc
		refreshTimeout      time.Duration
		refreshUnknownKID   bool
	}

		url := "http://keycloak:8080/auth/realms/{realm_id}/protocol/openid-connect/certs"

		refreshInterval := time.Hour
		options := keyfunc.Options{
			RefreshInterval: refreshInterval,
			RefreshErrorHandler: func(err error) {
				logging.Log.Printf("There was an error with the jwt.KeyFunc\nError: %s", err.Error())
			},
		}
		jwks, err := keyfunc.Get(url, options)

               // Parse the JWT.
	       verified_token, err := jwt.Parse(token, jwks.Keyfunc)
	       if err != nil {
		logging.Log.Fatalf("Failed to parse the JWT.\nError: %s", err.Error())
	       }

	      // Check if the token is valid.
	      if !verified_token.Valid {
		logging.Log.Fatalf("The token is not valid.")
		return false
	      }
		if err != nil {
			logging.Log.Fatalf("Failed to create JWKS from resource at the given URL.\nError: %s", err.Error())
			return false
		}
	      } else {
		fmt.Println(err)
	      }

	fmt.Println("Token is valid")
	return true
}

```

## Version 
	github.com/MicahParks/keyfunc v1.0.0

**Comment by MicahParks** [comment]
Hmmm... Looking at this, it seems it's actually a panic in the `github.com/coralogix/go-coralogix-sdk` package. Particularly, [this line](https://github.com/coralogix/go-coralogix-sdk/blob/74e702812387733fb04a1280dea65fbe4724ad61/manager.go#L136).

The Go panic stack looks like it doesn't contain any code from `github.com/MicahParks/keyfunc` or `github.com/golang-jwt/jwt/v4`. Looking into the `github.com/coralogix/go-coralogix-sdk` package, I'm pretty sure your issue is either:
* Improper arguments passed to the logging library, make sure to read the docs thoroughly.
* A bug in the `github.com/coralogix/go-coralogix-sdk` package.

I'm pretty confident that there's at least one bug in the `github.com/coralogix/go-coralogix-sdk` package. I actually made a GitHub issue for it. You can view the issue here: https://github.com/coralogix/go-coralogix-sdk/issues/9

I'd like to see your issue resolved, but I don't currently think you've stumbled across a `github.com/MicahParks/keyfunc` bug. If you're able to make a minimal working example that I can reproduce, I'd appreciate it if you could share that with me. You could visit the JWKS URL in your browser, copy/paste the response (which will be JSON) into a Go constant, then utilize [`keyfunc.NewJSON`](https://pkg.go.dev/github.com/MicahParks/keyfunc#NewJSON).
