### ISSUE TITLE
Migrate deprecated usage of io/ioutil

### ISSUE THREAD

**Issue by MicahParks** [MicahParks/keyfunc#42]
The `io/ioutil` package was marked as deprecated with the release of Go 1.16. All the functionality has been copied to either the `io` or `os` packages.

I believe this issue would be great for a first-time contributor. There aren't many usages of `io/ioutil` and it should be strait forward.

Here's the mapping of `ioutil` functions to their new, non-deprecated packages: https://go.dev/doc/go1.16#ioutil

**Comment by chriswolfdesign** [comment]
I took a shot at this.  Any change requests or questions are welcome and appreciated.

PR: https://github.com/MicahParks/keyfunc/pull/43

**Comment by MicahParks** [comment]
Exactly what I needed! Thank you for your contribution. :slightly_smiling_face: 

The change will be released in `v1.2.1`, which I'll write up right now.

**Comment by chriswolfdesign** [comment]
Happy to help.  I'm trying to develop my Golang skills so if you ever find yourself in need of some more contribution, don't hesitate to send me a message.

**Comment by MicahParks** [comment]
Relevant release: https://github.com/MicahParks/keyfunc/releases/tag/v1.2.1
