### ISSUE TITLE
Add support for x5c (X.509 certificate chain)

### ISSUE THREAD

**Issue by MicahParks** [MicahParks/keyfunc#45]
GitHub insights regularly shows me that one of the top searched things in this project is `x5c` (X.509 certificate chain). To my knowledge a minimal implementation of a JWK Set does _not_ require an `x5c` and other _required_ assets such as `n` (modulus) and `e` (exponent) would cover the narrow scope of this project.

If this were to be implemented, the `x5c` would only be considered after RFC required assets were found missing. For example, if a JWK identified a key as an RSA key:
* If the JWK contained `n`, `e`, and `x5c`, this package would parse the key using `n` and `e`.
* If the JWK was missing `n` and or `e` but the contained `x5c`, this package would parse the key using `x5c`.
The order in which assets are considered might be configurable, but the default behavior would be as described above.

I don't know the motivation of the users searching for `x5c`. Perhaps it's due to how recognizable X.509 certificates are or maybe it's due to a non-RFC compliant implementation of a JWK Set where only `x5c` is provided. I think supporting and maintaining `x5c` would be non-trivial so I would be less likely to include it in the code base for the former reason, but would want to help any users in the latter case.

If this issue would help your use case, please comment to help clarify common use cases for me. Otherwise, if you'd like to see this implemented, please react with an emoji :+1:

**Comment by jarleriksen** [comment]
Hi,

We ran into this error `x509: certificate signed by unknown authority` from Keycloak when we were deploying to staging which were running on HTTPS.
I don't know if this is specific to our Keycloak setup or if it's a general thing but I seem to remember that I saw you have it working from a HTTPS url.

I can request the `/openid-connect/certs` endpoint fine from anywhere else than through this library. Do you have any insights?
I have seen people solve this by disabling TLS insecure verification but we don't want to do that.

Thanks!

**Comment by MicahParks** [comment]
From the information given, it's unclear to me where your problem originates.

Without further details, I believe this isn't related to this GitHub issue, or even this project, `keyfunc`.

This issue, specifically is regarding the JSON attribute `x5c` in a JSON Web Key (JWK). There's an example below:
```json
    {
      "kid": "arlUxX4hh56rNO-XdIPhDT7bqBMqcBwNQuP_TnZJNGs",
      "kty": "RSA",
      "alg": "RS512",
      "use": "sig",
      "n": "hhtifu8LL3ICE3BAX5l1KZv6Lni0lhlhBusSfepnpxcb4C_z2U71cQTnLY27kt8WB4bNG6e5_KMx9K3xUdd3euj9MCq8vytwEPieeHE1KXQuhJfLv017lhpK_dRMOHyc-9-50YNdgs_8KWRkrzjjuYrCiO9Iu76n5319e-SC8OPvNUglqxp2N0Sp2ltne2ZrpN8T3OEEXT62TSGmLAVopRGw5gllNVrJfmEyZJCRrBM6s5CQcz8un0FjkAAC4DI6QD-eBL0qG3_NR0hQvR1he2o4BLwjOKH45Pk_jj-eArp-DD6Xq6ABQVb5SNOSdaxl5lnmuotRoY3G5d9YSl-K3w",
      "e": "AQAB",
      "x5c": [
        "MIICmzCCAYMCBgF4HSCcDzANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAZtYXN0ZXIwHhcNMjEwMzEwMTcxMTE5WhcNMzEwMzEwMTcxMjU5WjARMQ8wDQYDVQQDDAZtYXN0ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCGG2J+7wsvcgITcEBfmXUpm/oueLSWGWEG6xJ96menFxvgL/PZTvVxBOctjbuS3xYHhs0bp7n8ozH0rfFR13d66P0wKry/K3AQ+J54cTUpdC6El8u/TXuWGkr91Ew4fJz737nRg12Cz/wpZGSvOOO5isKI70i7vqfnfX175ILw4+81SCWrGnY3RKnaW2d7Zmuk3xPc4QRdPrZNIaYsBWilEbDmCWU1Wsl+YTJkkJGsEzqzkJBzPy6fQWOQAALgMjpAP54EvSobf81HSFC9HWF7ajgEvCM4ofjk+T+OP54Cun4MPperoAFBVvlI05J1rGXmWea6i1Ghjcbl31hKX4rfAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAB7bpwPoL02WGCCVhCsbDkq9GeFUwF01opVyFTijZlTUoTf5RcaR2qAH9/irkLjZeFeyozzC5mGvIVruBwnx/6l4PcAMxKK4YiheFVoO/dytpGMCj6ToNmKpjlXzOLAHelieWIUDtAFSYzENjIO01PyXTGYpxebpQCocJBvppj5HqARS9iNPcqBltMhxWrWmMu81tOG3Y7yd2xsIYXk6KjaoefLeN8Was4BPJ0zR6tTSEm6ZOvSRvlppqh84kz7LmWem7gGHAsY2G3tWBUmOdO/SMNMThqV62yLf7sKsuoE1w06lfmrf6D2zGwoEyz+TT6fdSkc34Yeh7+c01X6nFWU="
      ],
      "x5t": "geiCPGtT_10T8xGLUK1LA0_YQEE",
      "x5t#S256": "dLp3_QNGwMbYll5VecnR8Q9NSeFVfqJPBTa2_8qf48I"
    }
```

If I had to guess, your issue is arising from the _operating system_ not recognizing the self-signed certificate that Keycloak is using for HTTPS. So your solution would be to load the self signed certificate into the operating systems running your code. Note that if you are using Docker containers, the best place to load this certificate is in the `Dockerfile`, when your image is being created (easier) or on container startup, if you need to dynamically select a certificate to load (harder). Alternatively, you could load the certificate dynamically through your Golang application. I think this would involve custom code using the [`crypto/x509` package](https://pkg.go.dev/crypto/x509) (hardest).

If I've guessed correctly, the problem being described isn't related to this GitHub issue, but I wish you the best of luck anyways. If I've misinterpreted your problem, could you provide more details like exactly how that error was produced or if Keycloak is using a self signed certificate?

**Comment by jarleriksen** [comment]
Thank you so much for your answer! Sorry for hijacking your issue. I misinterpreted the issue.
I believe your suggestion will fix the problem.

Thanks again!

**Comment by MicahParks** [comment]
I'm closing this issue for now. I haven't seen anyone present a use case.

Please feel free to comment, it may be reopened.
