### ISSUE TITLE
backgroundRefresh on nil jwks

### ISSUE THREAD

**Issue by suntriber** [MicahParks/keyfunc#64]
Upon implementing and testing this package I noticed that if the initial call to `(*JWKS).refresh()` fails nil is returned as the `*jwks`.
`	err = jwks.refresh()
	if err != nil {
		return nil, err
	}`

As a consequence of this no further refreshing is done. Would it be possible to implement some functionality to allow a backgroundRefresh to be done even if the initial call to request gives an error? Hope my question is clear enough.

**Comment by MicahParks** [comment]
The `.refresh` method is not exported to package users. Perhaps you mean [`keyfunc.Get`](https://pkg.go.dev/github.com/MicahParks/keyfunc#Get)?

If that's what was meant, it may be possible that the error from this portion is not `nil`. In this case, the error needs to be checked and handled by the package user.
https://github.com/MicahParks/keyfunc/blob/master/get.go#L45-L48

It's possible I missed something, but I'd likely need more details. Are you able to write a complete example that reproduces the behavior you've found to be unexpected?

**Comment by suntriber** [comment]
Yes, I did mean `keyfunc.Get()`.
And yes, exactly those lines, if the error is not `nil` it means that the `jwks`variable will be nil. Say for instance that the request times out on reboot, but one would like the keyfunc package to keep refreshing and trying the endpoint no matter. I can live with that this is something that should be handled by the package user, but was merely wondering if it would be a wanted feature to add this functionality in the package.

Small example to demonstrate:
```golang
func main() {
	jwks, err := keyfunc.Get(jwksEndpointURL, keyfunc.Options{
		RefreshInterval: time.Minute,
	})
	if err != nil {
		// simply warn that we had a problem, rather than closing
		log.Warnf("error retrieving keys, %v", err)
	}

	// further down in program, we might get a request to process a token
	if jwks == nil {
		// deny request, we dont have keys
	} else {
		// process token
	}

	// next time get a request, jwks might have been refreshed and we can process
}```

My point is that if the refresh were allowed still, even though we had an error first time, it might be a nice feature rather than having to implement retry logic by your self. Hope I made myself clearer.

**Comment by MicahParks** [comment]
From my perspective, it appears all the behavior is expected.

> might be a nice feature rather than having to implement retry logic by your self

Currently, there is no automatic retry feature in `keyfunc`. Without any changes to the `keyfunc` package, I would recommend not proceeding with `nil` `*keyfunc.JWKS` and handling the error via retries in the calling code by blocking.

I'm not sure if an automatic retry feature in the `keyfunc` package is a feature I'd like to add. An automatic retry feature that asynchronously (non-blocking) retrieves the JWK Set may cause a different class of more complex unexpected behavior, a JWT might be not validated by the application at one moment, but the same JWT validated at a later time. There is a way to include automatic retries that would block via a function, but at this time, I think that's best left up to the package user.

I would recommend designing applications to gather all required connections (like databases/`keyfunc`) and assets in a blocking manner before allowing the application to proceed and failing to start the business logic if there is an error unsolved by retries. In my experience, it helps reduce complexities and the variety of errors. For `keyfunc`, there's the extra note that it can reuse an old JWK Set it has from last time if a non-critical refresh fails. Unfortunately, if a critical refresh fails in `keyfunc`, it needs to be handled asynchronously through `RefreshErrorHandler` in [`keyfunc.Options`](https://pkg.go.dev/github.com/MicahParks/keyfunc#Options)

**Comment by suntriber** [comment]
I understand your reasoning and thank you for the quick response.

**Comment by ErenDursun** [comment]
Hi, first of all: thanks for this great repository!

I have a similar issue, but with the GetMultiple method instead of the Get method:

When using keyfunc.GetMultiple to retrieve JWKs from multiple URLs with a configuration to refresh those keys, then during runtime some of the URLs might have a downtime and when they are up again all will self-heal after a background refresh - and that's neat!

But what if one of many URLs isn't accesible at startup, due to let's say maintenance? In that case blocking and waiting for all URLs to be ready like in @suntriber s use case might not be necessary, because the service could still handle _most_ requests. Can we have the keyfunc.GetMultiple function still load from all working URLs and have the rest loaded later via background refresh?

So far I couldn't find a way to achieve this from outside the library without reimplementing large parts of it. But adding a new parameter to the keyfunc.Options could solve this in a much simpler way.

What's your opinion on that? Is my use-case too niche, or would others also like to have that?

**Comment by MicahParks** [comment]
@ErenDursun, that is pretty niche. However, that may be easy to support through `keyfunc.Options`. Why don't you create a separate issue requesting this and I'll see if I can implement it after work?

**Comment by MicahParks** [comment]
@suntriber I think the newly added feature supports your initial use case. See #90 and the associated pull request for more details. It's possible I didn't full understand the issue on the first go around or didn't see the value until the `keyfunc` project supported multiple JWK Sets natively.

**Comment by suntriber** [comment]
Hi,
Yes this newly added feature does indeed support my use case. I did however implement a work around but next refactoring I'll certainly consider using this instead as it would remove some complexity from our code base.
Thanks for the tag and kudos for a great lib!
