### ISSUE TITLE
Avoid creation of unidirectional channel

### ISSUE THREAD

**Issue by tcriess** [MicahParks/keyfunc#81]
In the refresh loop (in backgroundRefresh), there is a `make(<-chan time.Time)` - while i understand its purpose, it would be nice to avoid creating a unidirectional channel, as this seems to prevent executing the code via yaegi (and thus in a traefik plugin). I am not entirely sure why exactly this is a problem, but probably it is a limitation of yaegi, which panics when trying to execute this statement. Maybe there is a more elegant way than what I am using as a quick fix at the moment (an if-condition before the select to use it with or without a `<-time.After` case).

**Comment by MicahParks** [comment]
Thank you for submitting this issue @tcriess.

Would you please provide steps to reproduce this issue and the copy/paste of the error or panic you experience at the end of these steps?

**Comment by tcriess** [comment]
1. create a traefik plugin (f.e. based on the example plugin), based on the traefik documentation https://doc.traefik.io/traefik/plugins/
2. use github.com/MicahParks/keyfunc and github.com/golang-jwt/jwt/v4 in this plugin for verifying a jwt like so
```
options := keyfunc.Options{
	Ctx: ctx,
	RefreshErrorHandler: func(err error) {
		log.Printf("error: there was an error with the jwt.Keyfunc: %s", err.Error())
	},
	RefreshInterval:   time.Hour,
	RefreshRateLimit:  time.Minute * 5,
	RefreshTimeout:    time.Second * 10,
	RefreshUnknownKID: true,
}

jwks, err := keyfunc.Get(jwksUrl, options)
if err != nil {
	return nil, err
}
```
3. start traefik using this plugin. Traefik will panic with
```
panic: reflect.MakeChan: unidirectional channel type [recovered]              
        panic: reflect.MakeChan: unidirectional channel type                  
                                                                              
goroutine 114 [running]:                                                      
github.com/traefik/yaegi/interp.runCfg.func1()                                
        github.com/traefik/yaegi@v0.15.0/interp/run.go:205 +0x13b
panic({0x3a3ed60, 0x529f910})
        runtime/panic.go:884 +0x212
```

traefik uses yaegi, a runtime go interpreter for its plugins, which heavily uses reflection - and thus unidirectional channels cannot be created. At least that is my interpretation.
Meanwhile I discovered that the token verification does not work even if a workaround for the unidirectional channel is in place (golang-jwt complains about a wrong key type...). So I'll close this issue as there seems to be more to investigate than just the unidirectional channel - and there is an alternative at https://github.com/team-carepay/traefik-jwt-plugin which I should have looked at earlier :).
