### ISSUE TITLE
github.com/dgrijalva/jwt-go is no longer maintained

### ISSUE THREAD

**Issue by zak905** [MicahParks/keyfunc#9]
This library is quiet useful, and fills an important gap when working with jwk in jwt-go, however I have seen that github.com/dgrijalva/jwt-go have been migrated to github.com/golang-jwt/jwt, so I guess this should follow up as well

**Comment by MicahParks** [comment]
Glad to see you find this project useful!

Thanks for the heads up about the official move. For anyone who hasn't seen the source already, please view it here: https://github.com/dgrijalva/jwt-go/issues/462

I'll be updating [`JWKs.KeyFunc`](https://pkg.go.dev/github.com/MicahParks/keyfunc#JWKs.KeyFunc) method to support `github.com/golang-jwt/jwt` and move support for `github.com/dgrijalva/jwt-go` to `JWKS.LegacyKeyFunc`. This will be in `v0.6.0`. Development for that release will begin today.

The [`JWKs.KeyFuncF3T`](https://pkg.go.dev/github.com/MicahParks/keyfunc#JWKs.KeyFuncF3T) method will remain unchanged.

**Comment by zak905** [comment]
Awesome, looking forward to test

**Comment by MicahParks** [comment]
Closing this issue as `v0.6.0` has been released.
